/**
 * pi.cc-connect plugin backend.
 *
 * Bridges the work-panel view (via onPanelInvoke) to the host's CC Connect
 * controller (pi.ccConnect.*) and owns the PI-managed cc-connect
 * configuration: a generated config.toml plus a bindings.json mapping
 * conversation keys to PI projects/sessions. Nothing here touches
 * ~/.cc-connect and nothing is downloaded; the daemon is started from a
 * locally-detected executable only.
 */
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const BINDINGS_KEY = "ccConnectBindings";

const DEFAULT_SETTINGS = Object.freeze({
  command: "",
  autoStartDaemon: false,
  [BINDINGS_KEY]: [],
});

function createPanel({ pi }) {
  let dataPath = null;

  function ensurePaths() {
    if (dataPath) return dataPath;
    dataPath = pi.plugin.getDataPath();
    fs.mkdirSync(path.join(dataPath, "config"), { recursive: true });
    return dataPath;
  }

  function configPath() {
    return path.join(ensurePaths(), "config", "config.toml");
  }

  function bindingsPath() {
    return path.join(ensurePaths(), "bindings.json");
  }

  async function loadBindings() {
    const settings = (await pi.plugin.getSettings()) || {};
    const bindings = settings[BINDINGS_KEY];
    return Array.isArray(bindings) ? bindings : [];
  }

  /** Bindings file for the `pidesktop` backend: key → resolution rule. */
  function bindingsFileContent(bindings) {
    const map = {};
    for (const binding of bindings) {
      if (!binding || typeof binding.key !== "string" || !binding.key.trim()) continue;
      map[binding.key.trim()] = {
        ...(binding.projectId ? { projectId: String(binding.projectId) } : {}),
        ...(binding.sessionId ? { sessionId: String(binding.sessionId) } : {}),
        mode: binding.mode === "fixed" || binding.mode === "latest" ? binding.mode : "new",
      };
    }
    return `${JSON.stringify(map, null, 2)}\n`;
  }

  function writeFiles(bindings, tokenFile) {
    if (!tokenFile) throw new Error("bridge token file path is unavailable; enable the bridge first");
    fs.writeFileSync(bindingsPath(), bindingsFileContent(bindings), { encoding: "utf8", mode: 0o600 });
    fs.writeFileSync(configPath(), renderConfigToml(tokenFile), { encoding: "utf8", mode: 0o600 });
  }

  /** PI-managed configuration: never writes into ~/.cc-connect. The backend
   * reads the bridge URL/token from the desktop's 0600 discovery files. */
  function renderConfigToml(tokenFile) {
    return [
      "# Generated by the pi.cc-connect plugin (PI-Desktop).",
      "# PI-managed: this file lives under the plugin data directory, not ~/.cc-connect.",
      "",
      "[log]",
      'level = "info"',
      "",
      "[projects.agent]",
      'type = "pidesktop"',
      "",
      "[projects.agent.options]",
      `token_file = "${tokenFile}"`,
      `bindings_file = "${bindingsPath()}"`,
      'binding_mode = "bindings"',
      'permission_mode = "ask"',
      "",
    ].join("\n");
  }

  async function writeFilesWithStatus(bindings) {
    const status = await pi.ccConnect.status();
    writeFiles(bindings, status.paths.tokenFile);
  }

  async function statusPayload() {
    const status = await pi.ccConnect.status();
    const binary = await pi.ccConnect.detectBinary();
    const bindings = await loadBindings();
    return {
      status,
      binary,
      bindings,
      paths: { config: configPath(), bindings: bindingsPath() },
    };
  }

  async function handle(channel, payload = {}) {
    switch (channel) {
      case "status":
        return statusPayload();
      case "enableBridge": {
        await pi.ccConnect.setBridgeEnabled(payload.enabled === true);
        return statusPayload();
      }
      case "startDaemon": {
        ensurePaths();
        const bindings = await loadBindings();
        await writeFilesWithStatus(bindings);
        const settings = (await pi.plugin.getSettings()) || DEFAULT_SETTINGS;
        const started = await pi.ccConnect.startProcess({
          ...(payload.command || settings.command ? { command: payload.command || settings.command } : {}),
          args: ["--config", configPath()],
        });
        if (!started.running) {
          throw new Error("cc-connect exited immediately; check the logs for details");
        }
        return statusPayload();
      }
      case "stopDaemon":
        await pi.ccConnect.stopProcess();
        return statusPayload();
      case "restartDaemon": {
        ensurePaths();
        await writeFilesWithStatus(await loadBindings());
        return { ...(await pi.ccConnect.restartProcess()), ...(await statusPayload()) };
      }
      case "logs":
        return pi.ccConnect.logs({ limit: Math.min(Math.max(Number(payload.limit) || 200, 1), 1000) });
      case "bindings.save": {
        const bindings = Array.isArray(payload.bindings) ? payload.bindings : [];
        await pi.plugin.setSettings({ [BINDINGS_KEY]: bindings });
        await writeFilesWithStatus(bindings);
        return { bindings };
      }
      case "paths":
        return { config: configPath(), bindings: bindingsPath() };
      default:
        throw new Error(`unknown channel: ${channel}`);
    }
  }

  return {
    handle,
    // Exposed for tests and diagnostics.
    internals: { bindingsFileContent, renderConfigToml, configPath, bindingsPath, loadBindings },
  };
}

let panel = null;

module.exports = {
  async onLoad(api) {
    panel = createPanel({ pi: api });
  },
  async onUnload() {
    panel = null;
  },
  async onPanelInvoke(channel, payload) {
    if (!panel) throw new Error("pi.cc-connect is not loaded");
    return panel.handle(channel, payload);
  },
  // Test seam: build the handler against an injected host API.
  __createPanel: createPanel,
};
